<?php
add_action('admin_init', 'custom_theme_options');
function custom_theme_options()
{
  $saved_settings = get_option('option_tree_settings', array());
  $custom_settings = array(
    'contextual_help' => array(
      'sidebar'       => ''
    ),
    'sections'        => array(
      array(
        'id'          => 'general',
        'title'       => '<i class="fa fa-cogs"></i>General'
      ),
      array(
        'id'          => 'menu',
        'title'       => '<i class="fa fa-bars"></i>Menu'
      ),
      array(
        'id'          => 'social_share',
        'title'       => '<i class="fa fa-share-square"></i>Social Sharing'
      ),
      array(
        'id'          => 'homepage',
        'title'       => '<i class="fa fa-home"></i>Home page'
      ),
      array(
        'id'          => 'side_bar',
        'title'       => '<i class="fa fa-list"></i>Side bar'
      ),
      array(
        'id'          => 'section_customize',
        'title'       => '<i class="fa fa-layer-group"></i>Section customize'
      ),
      array(
        'id'          => 'customize_hot_and_popular',
        'title'       => '<i class="fa fa-table"></i>Customize hot and popular'
      ),
    ),
    'settings'        => array(
      array(
        'id'          => 'favicon',
        'label'       => 'Favicon',
        'desc'        => 'Upload favicon (.ico)',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'logo_image',
        'label'       => 'Logo Image',
        'desc'        => 'Upload your logo image',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'copyright',
        'label'       => 'Copyright Text',
        'desc'        => 'Appear in footer',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'general',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => ''
      ),
      array(
        'id'          => 'custom_script_header',
        'label'       => 'Custom scripts header',
        'desc'        => 'Enter custom code CSS or JS in header. Ex: <i>.body{ font-size: 13px; }</i>',
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => ''
      ),
      array(
        'id'          => 'custom_script_footer',
        'label'       => 'Custom script footer',
        'desc'        => 'Enter custom code or JS in footer. For example, enter Google Analytics',
        'std'         => '',
        'type'        => 'textarea-simple',
        'section'     => 'general',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'class'       => ''
      ),
      array(
        'id'          => 'menu_header',
        'label'       => 'Menu header',
        'desc'        => 'Create for list menu items in header',
        'std'         => '',
        'type'        => 'list-item',
        'section'     => 'menu',
        'settings'    => array(
          array(
            'label'       => 'Link',
            'id'          => 'link',
            'type'        => 'text',
            'desc'        => 'Enter link',
            'std'         => '',
          ),
          array(
            'label'       => 'Icon',
            'id'          => 'icon',
            'type'        => 'upload',
            'desc'        => 'Upload icon',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'menu_footer',
        'label'       => 'Menu footer',
        'desc'        => 'Create for list menu items in footer',
        'std'         => '',
        'type'        => 'list-item',
        'section'     => 'menu',
        'rows'        => '5',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => ''
      ),
      array(
        'id'          => 'share_facebook',
        'label'       => 'Facebook Share',
        'desc'        => 'Paste Facebook share link',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social_share',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'share_twitter',
        'label'       => 'Twitter Share',
        'desc'        => 'Paste Twitter share link',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social_share',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'share_linkedin',
        'label'       => 'LinkedIn Share',
        'desc'        => 'Paste LinkedIn share link',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social_share',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'share_youtube',
        'label'       => 'Youtube Share',
        'desc'        => 'Paste Youtube share link',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'social_share',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'custom_share',
        'label'       => 'Add custom share',
        'desc'        => 'Add more social share',
        'std'         => '',
        'type'        => 'list-item',
        'section'     => 'social_share',
        'settings'    => array(
          array(
            'label'       => 'Link share',
            'id'          => 'link_share',
            'type'        => 'text',
            'desc'        => '',
            'std'         => '',
          ),
          array(
            'label'       => 'Icon',
            'id'          => 'icon',
            'type'        => 'upload',
            'desc'        => 'Upload icon',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'homepage_title_short_description',
        'label'       => 'Title short description',
        'desc'        => 'Custom title for short description in homepage',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'homepage',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'homepage_short_description',
        'label'       => 'Short description',
        'desc'        => 'Custom short description in homepage',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'homepage',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'homepage_title_description',
        'label'       => 'Title description',
        'desc'        => 'Custom title for description in homepage',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'homepage',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'homepage_description',
        'label'       => 'Description',
        'desc'        => 'Custom description in homepage',
        'std'         => '',
        'type'        => 'textarea',
        'section'     => 'homepage',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'custom_section',
        'label'       => 'Add section',
        'desc'        => 'Create section in homepage',
        'std'         => '',
        'type'        => 'list-item',
        'section'     => 'homepage',
        'settings'    => array(
          array(
            'label'       => 'Select post',
            'id'          => 'post_select',
            'type'        => 'post-list',
            'desc'        => '',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'side_bar_game',
        'label'       => 'Side bar game',
        'desc'        => 'Display category to sidebar game',
        'std'         => '',
        'type'        => 'category-checkbox',
        'section'     => 'side_bar',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'side_bar_app',
        'label'       => 'Side bar app',
        'desc'        => 'Display category to sidebar app',
        'std'         => '',
        'type'        => 'category-checkbox',
        'section'     => 'side_bar',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'side_bar_hot_news',
        'label'       => 'Side hot news',
        'desc'        => 'Display youtube video to sidebar app',
        'std'         => '',
        'type'        => 'youtube-embed',
        'section'     => 'side_bar',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step' => '',
        'class'       => '',
      ),
      array(
        'id'          => 'section_blog',
        'label'       => 'Section blog',
        'desc'        => 'Customize for section blog',
        'std'         => '',
        'type'        => 'post-list-section-customize',
        'section'     => 'section_customize',
        'settings'    => array(
          array(
            'label'       => 'Select post',
            'id'          => 'post_select',
            'type'        => 'post-list-section-customize',
            'desc'        => '',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'section_tips_and_android',
        'label'       => 'Section tips and android',
        'desc'        => 'Customize for section tips and android',
        'std'         => '',
        'type'        => 'post-list-section-customize',
        'section'     => 'section_customize',
        'settings'    => array(
          array(
            'label'       => 'Select post',
            'id'          => 'post_select',
            'type'        => 'post-list-section-customize',
            'desc'        => '',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'section_news_tech',
        'label'       => 'Section news tech',
        'desc'        => 'Customize for section news tech',
        'std'         => '',
        'type'        => 'post-list-section-customize',
        'section'     => 'section_customize',
        'settings'    => array(
          array(
            'label'       => 'Select post',
            'id'          => 'post_select',
            'type'        => 'post-list-section-customize',
            'desc'        => '',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'customize_hot',
        'label'       => 'Tab hot',
        'desc'        => 'Create section popular by category',
        'std'         => '',
        'type'        => 'list-item',
        'section'     => 'customize_hot_and_popular',
        'settings'    => array(
          array(
            'label'       => 'Select post',
            'id'          => 'post_select',
            'type'        => 'post-list',
            'desc'        => '',
            'std'         => '',
          ),
        ),
      ),
      array(
        'id'          => 'customize_popular',
        'label'       => 'Tab popular',
        'desc'        => 'Create section popular by category',
        'std'         => '',
        'type'        => 'list-item',
        'section'     => 'customize_hot_and_popular',
        'settings'    => array(
          array(
            'label'       => 'Select post',
            'id'          => 'post_select',
            'type'        => 'post-list',
            'desc'        => '',
            'std'         => '',
          ),
        ),
      ),
    )
  );

  $custom_settings = apply_filters('option_tree_settings_args', $custom_settings);
  if ($saved_settings !== $custom_settings) {
    update_option('option_tree_settings', $custom_settings);
  }
}
