<?php

 // Auto generated by wpfluent Installer.

 return array (
  'name' => 'Ninja Tables',
  'slug' => 'ninja-tables',
  'domain_path' => '/language',
  'text_domain' => 'ninja-tables',
  'hook_prefix' => 'ninjatables',
  'rest_namespace' => 'ninjatables',
  'rest_version' => 'v2',
  'env' => 'dev',
);
